function install_sbmvivo
prevdir = cd;
basep = fileparts(mfilename('fullpath'));
if basep(end) ~= filesep, basep = [basep filesep]; end
p = { ...
    '' ...  % base directory    
    ['mex' filesep 'sbm_cuda'] ...
    ['mex' filesep 'sbm_fit'] ...
    'c2swrapper' ...
    'MLspikewrapper' ...
    'util' ...
    'analysis' ...
    'gui' ...
    'optelecdataformat'};
addpath(basep);
for k = 1:numel(p)
    
    addpath([basep p{k}]);
    
end
cd(prevdir);
savepath
%FIXME check whether mex files are compiled, and test them if GPU is
%present
