function r = apdet_resultsstruct(nseg)
nneurons = numel(nseg);
r = cell(1, nneurons);

v = 0.1;

for n = 1:nneurons
    
    r{n} = repmat(orderfields(struct( ...
        'spikecounts', [], ...
        'spikecount_times', [], ...
        'spiketimes', [], ...
        'spiketimes_window', nan(1, 2), ...
        'params', struct(), ...
        'opts', struct(), ...
        'outputvars', struct(), ...
        'resultsstruct_version', v ...
        )), 1, nseg(n));
    
end