function oedsinfo = empty_oedatasegmentinfo
oedatasegmentinfo_version = 0.19;
oedsinfo = orderfields(struct( ...
    'version', oedatasegmentinfo_version ...
    ,'excitationwavelength',NaN ...
    ,'indicator', '' ...
    ,'detectorname', '' ...
    ,'detectortype', '' ...
    ,'scanmode', '' ...
    ,'numericalaperture', '' ...
    ,'lens', '' ...
    ,'excitationsource', '' ...
    ,'acquisitionsoftware', '' ...
    ,'acquisitionsoftwareversion', '' ...
    ,'digitalsettingsindex', NaN ... %if these are the same for two setting, then the digital gain and offset are assumed to be the same
    ,'dwelltimeperimage', NaN ...
    ,'samplesperpixel', NaN ...
    ,'nA2D', NaN ... %number of analog-to-digital measurements averaged (not summed!) to make the fluorescence signal
    ,'darkoffsetcorrected', false ... %indicates whether the "dark" signal has been subtracted so that a fluorescence measurement of zero corresponds to a closed shutter
    ,'darkoffset', NaN ...
    ,'data_import_scale_factor', NaN ... %pixel values are multiplied by this to give something consistent across files
    ,'darknoise_sd_per_A2D', NaN ... standard deviation of noise on 1 A2D measurement when shutter is closed
    ,'settingsindex', NaN ... %indicates which segments share the same digital/analog settings BESIDES number of A2D measurements that may change DC offsets, SNR, etc. (PMT voltage, pixel dwell time, zoom factor, etc.). NaN indicates unknown
    ,'focalplaneindex', NaN ... %indicates which segments share the same focal plane, or "close to it". those with the same plane can be combined in feature extraction. NaN indicates unknown
    ,'zoomfactor', NaN ...
    ));