function ainfo = empty_apdetalginfo
ainfo = orderfields(struct( ...
    'version', 0.011 ...
    ,'name', '' ...
    ,'shortname', '' ...
    ,'notes', {{}} ...
    ,'ismaximumlikelihood', [] ...
    ,'isdeterministic', [] ...
    ,'algorithm_version', '' ...
    ));