function oerec = empty_oerec
%container for holding a single combined optical/electrical recording
%this object refers to a single neuron
oerec_version = 0.01;
oerec = orderfields(struct( ...
    'version', oerec_version ...
    ,'data', repmat(empty_oedatasegment,1,0) ...
    ,'info', empty_oerecinfo ...
    ,'name', '' ...
    ));