function oesim = empty_oesimulation
%oesim = empty_oesimulation
%structure describing simulation of a single neuron
oesim = orderfields(struct( ...
     'oerec',empty_oerec ...
    ,'simulation_method_name','','simulation_function','','simulation_method_version',NaN ...
    ,'model_parameters',struct(),'model_data',struct() ...
    ,'version', 0.01 ...
    ));