function oerecinfo = empty_oerecinfo
%information about a combined optical/electrical recording
%this object refers to a single neuron
oerecinfo_version = 0.011;
oerecinfo = orderfields(struct( ...
    'version', oerecinfo_version ...
    ,'species', '' ...
    ,'strain', '' ....
    ,'birthdate', '' ...
    ,'sex', '' ...
    ,'notes', {{}} ...
    ,'region', '' ... %location in the nervous system of the recorded neuron
    ,'attributes_qual',{{}} ...
    ,'attributes_quant',{{}} ...
    ,'values_quant', [] ... %double precision
    ));