function fi = default_oedatabrowser_fileinfostruct
fi = struct( ...
     'odbfile','' ...
    ,'odbdir',[fileparts(mfilename('fullpath')) filesep] ...
    ,'defaultfigsavedir',[fileparts(mfilename('fullpath')) filesep '..' filesep 'figs' filesep] ...
    ,'tmpdir', [fullfile(tempdir,['oedatabrowser_' char(java.util.UUID.randomUUID)]) filesep] ...
);