function oedb = empty_oedbstruct
oedb = struct('algnames',{{}},'algfunctions',{{}},'trainfunctions',{{}},'alginfo',empty_apdetalginfo,'algavailable',false(1,0), ...
    'sourcedatafiles',{{}},'datasetnames',{{}},'neuronnames',{{}},'segmentnames',{{}},...
    'ndatasets',0,'nneurons',zeros(1,0),'nsegments',{{}},'issimulation',false(1,0),...    
    'expanddataset',false(1,0),'expandneuron',{{}},'opt',oedb_defaultoptstruct,...
    'data',{{}},'results',{{}},'segcode',{{}} ...
    ,'stats', orderfields(struct('bydataset', repmat(empty_statstruct,0,0), 'byneuron', {{}}, 'bysegment', {{}})) ...
    ,'modified',false,'version',oedb_version);
oedb = orderfields(oedb);
