function s = empty_statstruct
s = struct( ...
    'corr_spikecounts', [], 'corr_spiketimes', [], ...
    'det_spikecounts', [], 'det_spiketimes', [], ...
    'fp_spikecounts', [], 'fp_spiketimes', [], ...
    'fr_est_spikecounts', [], 'fr_est_spiketimes', [], ...
    'fr_true_spikecounts', [], 'fr_true_spiketimes', [], ...
    'singleAP_rate_true', [], 'singleAP_detrate', [], ...
    'burst_detrate', [], ...
    'fp_spiketimes_anymatch', [], ...
    'totalT', [], 'totalspikes', [] ...
    );
fn = fieldnames(s);
for k = 1:numel(fn)
    
    s.([fn{k} '_sd']) = [];
    
end
s = orderfields(s);