function opt = oedb_defaultoptstruct %FIXME: should probably turn off storedatainmemory automatically when data on disk corresponds to at least some minimum predicted size in memory
opt = orderfields(struct(...
    'storedatainmemory',true,'figsavedir',[fileparts(mfilename('fullpath')) filesep '..' filesep 'figs' filesep] ...
    ,'expandonlyselected',true ...
    ,'tol_sec', 0.2 ...
    ));